service: open-graph-preview-demo
org: gjgdserverless
app: open-graph-preview-demo

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-admin

functions:
  main:
    handler: handlers.main
    events:
      - http:
          path: /{id}
          method: GET
